name: Deploy CELEX
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and run deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 75.119.135.119
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            /usr/local/bin/deploy-celex-all
